import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { title } from "process";
import Navbar from "../components/hlc/navbar/Navbar";
import { NavItems } from "../components/hlc/navbar/navitems";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar brand="IHSB" links={NavItems}></Navbar>
    </div>
  );
};

export default Home;
